"""Event topic constants for ShengWen application workflows."""

TASK_CREATED = "task.created"
TASK_STATUS_CHANGED = "task.status_changed"
TASK_COMPLETED = "task.completed"
TASK_FAILED = "task.failed"
TASK_CANCELLED = "task.cancelled"
TASK_DELETED = "task.deleted"
MODEL_LOAD_REQUESTED = "model.load_requested"
MODEL_LOAD_STARTED = "model.load_started"
MODEL_LOADED = "model.loaded"
MODEL_LOAD_FAILED = "model.load_failed"
MODEL_UNLOADED = "model.unloaded"
STORAGE_CLEANUP_REQUESTED = "storage.cleanup_requested"
STORAGE_CLEANUP_COMPLETED = "storage.cleanup_completed"
STORAGE_QUOTA_WARNING = "storage.quota_warning"
