from __future__ import annotations

from typing import Protocol, runtime_checkable

from .type import FileRecord


@runtime_checkable
class StorageRepository(Protocol):
    async def register_file(self, record: FileRecord) -> None: ...
    async def get_files_by_task(self, task_id: str) -> list[FileRecord]: ...
    async def delete_file(self, path: str) -> None: ...
    async def get_total_size_bytes(self) -> int: ...
    async def get_expired_files(self) -> list[FileRecord]: ...

